spring.application.name=contract-generator

spring.datasource.url=jdbc:postgresql://localhost:5432/contract_generator
spring.datasource.username=postgres
spring.datasource.password=G@9510

spring.jpa.hibernate.ddl-auto=update

